baseURL = "//lifeguard-dictionaries-30240.netlify.com/"
languageCode = "en-GB"
title = "Matt40k"
theme = "hyde"
[params]
  description = "Developer based in Ipswich, Suffolk, UK"
  copyright = "Matt Smith"