baseURL = "https://matt40k.uk/"
languageCode = "en-gb"
defaultContentLanguage = "en"
title = "Matt40k"
theme = "papercss-hugo-theme"
googleAnalytics = "UA-47831226-3"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  homeMetaContent = "Matt Smith - Developer from Ipswich, Suffolk, UK"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "02 Jan 06"

[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
