baseURL = "//matt40k.uk/"
languageCode = "en-GB"
title = "Matt40k"
theme = "hyde"
enableRobotsTXT = true	# Build robots.txt file
googleAnalytics = "UA-47831226-3"
Paginate = 3
enableGitInfo = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Developer based in Ipswich, Suffolk, UK"
  copyright = ""
  themeColor = "theme-base-09"
  layoutReverse = true
  GitHubUser = "matt40k"
  twitter = "matt40k"
  linkedin = "https://www.linkedin.com/in/matt40k/"

[params.social]
  facebook = "matt40k"
  github = "matt40k"
  linkedin = "matt40k"
  twitter = "matt40k"

[permalinks]
  post = "/:year/:month/:title/"
