baseURL = "//matt40k.uk/"
languageCode = "en-GB"
title = "Matt40k"
theme = "hyde"
enableRobotsTXT = true	# Build robots.txt file

[params]
  description = "Developer based in Ipswich, Suffolk, UK"
  copyright = ""
  themeColor = "theme-base-09"
  layoutReverse = true